apiVersion: v1
kind: Service
metadata:
  name: app-lb
spec:
  selector:
    app: app-lb
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: shabana-app
spec:
  selector:
    matchLabels:
      app: app-lb
  template:
     metadata:
        labels:
          app: app-lb  
     spec:    
      containers:
        - name: shabana-cluster
          image: shabana-app
          ports:
          - containerPort: 80
